version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - restore_cache:
          keys:
            - sfdx-7.81.0-local
      - run:
          name: sfdx install
          command: |
            if [ ! -d node_modules/sfdx-cli ]; then
                export SFDX_AUTOUPDATE_DISABLE=true
                export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
                export SFDX_DOMAIN_RETRY=300
                npm install sfdx-cli@7.81.0
                node_modules/sfdx-cli/bin/run --version
                node_modules/sfdx-cli/bin/run plugins --core
            fi
      - save_cache:
          key: sfdx-7.81.0-local
          paths:
            - node_modules
      - run:
          name: scratch org creation
          command: |
            mkdir keys
            echo $SFDC_SERVER_KEY | base64 -d > keys/server.key
            node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile keys/server.key --username $USERNAME --setdefaultdevhubusername -a DevHub
            node_modules/sfdx-cli/bin/run force:org:create -v DevHub -s -f config/project-scratch-def.json -a scratch
      - run:
          name: Remove Server Key
          when: always
          command: |
            rm assets/server.key
      - run:
          name: Push source to scratch org
          command: |
            node_modules/sfdx-cli/bin/run force:source:push -u scratch
      - run:
          name: Run Apex Tests
          command: |
            mkdir ~/tests
            mkdir ~/tests/apex
            node_modules/sfdx-cli/bin/run force:apex:test:run -u scratch -c -r human -d ~/tests/apex -w 9999
      - run:
          name: Delete scratch org
          when: always
          command: |
            node_modules/sfdx-cli/bin/run force:org:delete -u scratch -p
            rm ~/tests/apex/*.txt ~/tests/apex/test-result-7*.json
      - store_artifacts:
          path: ~/tests
      - store_test_results:
          path: ~/tests
workflows:
  version: 2
  validate:
    jobs:
      - build
